import numpy as np

# --- Simulation Parameters ---
GRAVITY = 9.81
BALL_MASS = 1.0
TIME_STEP = 0.02  # 50 Hz simulation frequency
FORCE_MAGNITUDE = 20.0  # Max force applied by controller

# --- Pygame Visualization Parameters ---
SCREEN_WIDTH = 400
SCREEN_HEIGHT = 600
BALL_RADIUS = 20
GROUND_HEIGHT = 50

# --- Colors ---
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

# --- RL Training Parameters ---
PPO_TIMESTEPS = 20000000
MAX_EPISODE_STEPS = 2000

# --- Environment Settings ---
TARGET_HEIGHT = 300.0
RANDOM_REFERENCE = False #True/False
MOVING_REFERENCE = True #True/False
MOVING_REFERENCE_TYPE = 'sigmoid'  # 'sine' or 'sigmoid'
SINE_REFERENCE_PERIOD = 0.01
SINE_REFERENCE_AMPLITUDE = 50
SIGMOID_REFERENCE_AMPLITUDE = 100
SIGMOID_REFERENCE_PERIOD = 1
SIGMOID_REFERENCE_SLOPE = 10
SIGMOID_REFERENCE_SHIFT = np.pi / (2 * SIGMOID_REFERENCE_PERIOD)

# --- EKF Parameters ---
EKF_VAR_PROC_POS = 2
EKF_VAR_PROC_VEL = 2
EKF_VAR_MEAS_POS = 36
EKF_VAR_MEAS_VEL = 9

# --- MHE Parameters ---
MHE_HORIZON = 5
MHE_VAR_PROC_POS = 2
MHE_VAR_PROC_VEL = 2
MHE_VAR_MEAS_POS = 36
MHE_VAR_MEAS_VEL = 9

# --- Standard MPC Parameters ---
STD_MPC_HORIZON = 5
STD_MPC_QH = 100
STD_MPC_QV = 10
STD_MPC_R = 1
STD_MPC_TERMINAL = 10
STD_MPC_DELTA_U_MAX = 15

# --- Stochastic MPC Parameters ---
STOCHASTIC_MPC_HORIZON = 5
STOCHASTIC_MPC_SAMPLES = 15
STOCHASTIC_MPC_QH = 100
STOCHASTIC_MPC_QV = 10
STOCHASTIC_MPC_R = 1
STOCHASTIC_MPC_TERMINAL = 10
STOCHASTIC_MPC_DELTA_U_MAX = 15

# --- Tube MPC Parameters ---
TUBE_MPC_HORIZON = 5
TUBE_MPC_QH = 100
TUBE_MPC_QV = 10
TUBE_MPC_R = 1
TUBE_MPC_TERMINAL = 10
TUBE_MPC_DELTA_U_MAX = 15
TUBE_MPC_TIGHTING_X = 1
TUBE_MPC_TIGHTING_U = 0.5
